# Generated by Django 6.1 on 2026-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='entry_type',
            field=models.CharField(choices=[('dr', 'Debit'), ('cr', 'Credit')], default='cr', max_length=2),
        ),
    ]
