# Generated by Django 6.1 on 2026-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('expense', 'Expense'), ('loan_repayment', 'Loan Repayment'), ('loan_disbursement', 'Loan Disbursement'), ('fine', 'Fine'), ('income', 'Income'), ('interest', 'Interest'), ('fine_redistribution', 'Fine Redistribution')], default='contribution', max_length=20),
        ),
    ]
