# Generated by Django 6.1 on 2026-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_expense_payment_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='applies_to_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
