# Generated by Django 6.1 on 2026-08-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='savings.savingsaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
