# Generated by Django 6.1 on 2026-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('expense_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('excluded_accounts', models.ManyToManyField(blank=True, related_name='excluded_expenses', to='savings.savingsaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
