# Generated by Django 6.1 on 2026-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('accountant', 'Accountant'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
