# Generated by Django 6.1 on 2026-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fd_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('fd_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration_years', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('excluded_accounts', models.ManyToManyField(blank=True, related_name='excluded_fds', to='savings.savingsaccount')),
                ('participant_accounts', models.ManyToManyField(blank=True, related_name='fds', to='savings.savingsaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
