# Generated by Django 6.1 on 2026-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('income', 'Income'), ('interest', 'Interest'), ('fine_redistribution', 'Fine Redistribution')], default='income', max_length=20),
        ),
    ]
