# Generated by Django 6.1 on 2026-09-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_income_type'),
        ('payments', '0006_payment_expense_payment_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_redistribution_income', to='payments.payment'),
        ),
    ]
